### ISSUE TITLE
wlan1 Scan issues 

### ISSUE THREAD

**Issue by qqbbpsy** [Cod3dDOT/aircrack-gui#5]
I have 2 WiFi adapters and only wlan0 laptops wifi adapter can scan networks, external wlan1 gives error. 
Thanks for your project
![wlan1](https://user-images.githubusercontent.com/45928848/137420144-f9f84506-0bb2-4bfe-9ff7-185149c7fcad.png)
!

**Comment by Cod3dDOT** [comment]
Hi! It seems the issue appears when a network with WPA1 encryption is found. I'll look into it, thanks for taking time and reporting.

**Comment by Cod3dDOT** [comment]
Pushed an update a minute ago. Hope it fixes the issue.

**Comment by qqbbpsy** [comment]
> Pushed an update a minute ago. Hope it fixes the issue.

Fixed! Thank you!

**Comment by qqbbpsy** [comment]
also, if it's possible it will be good to have a --nokill command when using 2 wifi adapters to don't drop the whole networking and to be to use one adapter keep connected to internet
